services:
  valkey:
    image: valkey/valkey-bundle:9.1.2-alpine
    restart: unless-stopped
    volumes:
      - model_vectors:/data
    environment:
      - VALKEY_EXTRA_FLAGS=--save 60 1 --loglevel warning

  searchy:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - IMAGE_DIR=/app/images
      - VALKEY_HOST=valkey
    ports:
      - 5000:8000
    volumes:
      - ${IMAGE_DIR}:/app/images:ro
    depends_on:
      - valkey

volumes:
  model_vectors:
