services:
  valkey:
    image: valkey/valkey-bundle:9.1.2-alpine
    restart: unless-stopped
    environment:
      - VALKEY_EXTRA_FLAGS=--save 60 1 --loglevel warning
    volumes:
      - model_vectors:/data

  searchy:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - IMAGE_DIR=/app/images
      - THUMB_DIR=/app/thumbs
      - VALKEY_HOST=valkey
    ports:
      - 8000:5000
    volumes:
      - ${IMAGE_DIR}:/app/images:ro
      - model_thumbs:/app/thumbs
    depends_on:
      - valkey

volumes:
  model_vectors:
  model_thumbs:
